version: '3.8'

services:
  ui:
    build:
      context: ./berutek.ui
      dockerfile: Dockerfile
    container_name: berutek_ui
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped