version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    environment:
      POSTGRES_DB: berutek
      POSTGRES_USER: berutek
      POSTGRES_PASSWORD: Beru140206*.
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U berutek -d berutek"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge